version: 1.0.0.{build}
image: Visual Studio 2017

init:
- appveyor version

services: mssql2017
build: off
artifacts:
- path: db\test_db.dacpac
  name: Mydacpac
deploy:
- provider: Local
  Mydacpac.deploy_database: true
  Mydacpac.connection_string: Server=(local)\SQL2017;Database=my_app;Integrated security=SSPI;
